import React, { useState, useEffect } from "react";
import { UI } from "./components";

export default function Studio() {
  const [elements, setElements] = useState([
    { id: "1", type: "Navbar", props: { title: "My AI Studio App" } },
    { id: "2", type: "Heading", props: { text: "Welcome to PyReact Studio" } },
    { id: "3", type: "Text", props: { text: "Drag, drop, and edit properties. Changes compile back to app.pyreact in real time." } },
    { id: "4", type: "Card", props: { title: "Visual Card", content: "This is a card element built in PyReact." } }
  ]);
  
  const [selectedId, setSelectedId] = useState("1");
  const [generatedCode, setGeneratedCode] = useState("");
  const [activeTab, setActiveTab] = useState("props");
  const [toastMsg, setToastMsg] = useState("");

  const selectedElement = elements.find(el => el.id === selectedId);

  // Generate code string dynamically
  useEffect(() => {
    let codeStr = "# Generated by PyReact Studio (Low-Code/No-Code Editor)\n\n";
    codeStr += "server {\n}\n\n";
    codeStr += "component App():\n";
    codeStr += "    return (\n";
    codeStr += "        <UI.Page>\n";
    
    elements.forEach(el => {
      if (el.type === "Navbar") {
        codeStr += `            <UI.Navbar title="${el.props.title || "App"}" />\n`;
      } else if (el.type === "Heading") {
        codeStr += `            <UI.Heading>${el.props.text || "Heading"}</UI.Heading>\n`;
      } else if (el.type === "Text") {
        codeStr += `            <UI.Text>${el.props.text || "Text"}</UI.Text>\n`;
      } else if (el.type === "Card") {
        codeStr += `            <UI.Card title="${el.props.title || "Card"}">\n`;
        codeStr += `                <UI.Text>${el.props.content || "Content"}</UI.Text>\n`;
        codeStr += `            </UI.Card>\n`;
      } else if (el.type === "Button") {
        codeStr += `            <UI.Button>${el.props.label || "Click"}</UI.Button>\n`;
      } else if (el.type === "Input") {
        codeStr += `            <UI.Input label="${el.props.label || "Label"}" placeholder="${el.props.placeholder || ""}" />\n`;
      }
    });
    
    codeStr += "        </UI.Page>\n";
    codeStr += "    )\n";
    setGeneratedCode(codeStr);
  }, [elements]);

  const addElement = (type) => {
    const newId = String(Date.now());
    let defaultProps = {};
    if (type === "Navbar") defaultProps = { title: "New Navbar" };
    if (type === "Heading") defaultProps = { text: "New Heading" };
    if (type === "Text") defaultProps = { text: "New text content goes here..." };
    if (type === "Card") defaultProps = { title: "New Card", content: "Card content." };
    if (type === "Button") defaultProps = { label: "Action Button" };
    if (type === "Input") defaultProps = { label: "Input Field", placeholder: "Enter values..." };

    setElements([...elements, { id: newId, type, props: defaultProps }]);
    setSelectedId(newId);
  };

  const deleteElement = (id, e) => {
    e.stopPropagation();
    const filtered = elements.filter(el => el.id !== id);
    setElements(filtered);
    if (selectedId === id && filtered.length > 0) {
      setSelectedId(filtered[0].id);
    }
  };

  const updateProp = (key, value) => {
    setElements(elements.map(el => {
      if (el.id === selectedId) {
        return { ...el, props: { ...el.props, [key]: value } };
      }
      return el;
    }));
  };

  const moveElement = (index, direction, e) => {
    e.stopPropagation();
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= elements.length) return;
    const newElements = [...elements];
    const temp = newElements[index];
    newElements[index] = newElements[newIndex];
    newElements[newIndex] = temp;
    setElements(newElements);
  };

  const handleSave = async () => {
    try {
      const res = await fetch("/api/studio/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code: generatedCode })
      });
      const data = await res.json();
      if (data.status === "ok") {
        setToastMsg("Successfully saved & compiled app.pyreact!");
        setTimeout(() => setToastMsg(""), 3000);
      }
    } catch (e) {
      setToastMsg("Error saving code to backend.");
      setTimeout(() => setToastMsg(""), 3000);
    }
  };

  return (
    <div className="min-h-screen bg-[#070b13] text-white flex flex-col font-sans">
      {/* Top Navbar */}
      <header className="px-6 py-4 bg-[#0f172a]/95 border-b border-white/5 flex items-center justify-between backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center font-bold">P</div>
          <span className="font-extrabold text-lg tracking-tight bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent">
            PyReact Studio <span className="text-xs font-medium text-blue-400 bg-blue-400/10 px-2 py-0.5 rounded-full ml-1.5">v0.1</span>
          </span>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleSave} 
            className="px-4 py-2 bg-gradient-to-r from-blue-500 to-indigo-600 text-white rounded-lg font-semibold hover:opacity-90 shadow-lg shadow-blue-500/25 transition active:scale-95 text-sm"
          >
            Save to Disk (Compile)
          </button>
        </div>
      </header>

      {/* Main Workspace */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Toolbox Panel */}
        <aside className="w-72 bg-[#0b0f19] border-r border-white/5 p-5 flex flex-col gap-6">
          <div>
            <h3 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-3">Toolbox</h3>
            <p className="text-xs text-white/50 mb-4">Click component type to insert into visual workspace.</p>
            <div className="grid grid-cols-2 gap-3">
              {["Navbar", "Heading", "Text", "Card", "Button", "Input"].map(type => (
                <button
                  key={type}
                  onClick={() => addElement(type)}
                  className="p-3 bg-white/5 rounded-xl border border-white/5 hover:bg-white/10 hover:border-white/10 text-left transition flex flex-col gap-1.5"
                >
                  <span className="font-semibold text-sm">{type}</span>
                  <span className="text-[10px] text-white/40">Insert element</span>
                </button>
              ))}
            </div>
          </div>
        </aside>

        {/* Center Visual Canvas */}
        <main className="flex-1 bg-[#090d16] p-8 overflow-y-auto flex justify-center items-start">
          <div className="w-full max-w-2xl bg-[#0d1321] rounded-2xl border border-white/5 min-h-[500px] shadow-2xl p-6 relative">
            <div className="absolute top-3 left-4 text-[10px] font-mono text-white/20 uppercase tracking-wider">Visual Workspace Canvas</div>
            
            <div className="mt-8 space-y-4">
              {elements.length === 0 ? (
                <div className="text-center text-white/30 py-24 border-2 border-dashed border-white/5 rounded-xl">
                  Canvas is empty. Click items in the toolbox to build layout!
                </div>
              ) : (
                elements.map((el, idx) => {
                  const isSelected = el.id === selectedId;
                  return (
                    <div
                      key={el.id}
                      onClick={() => setSelectedId(el.id)}
                      className={`relative p-4 rounded-xl border transition cursor-pointer ${isSelected ? "border-blue-500 bg-blue-500/5 ring-1 ring-blue-500" : "border-white/5 bg-white/5 hover:border-white/10"}`}
                    >
                      {/* Floating Control Badges */}
                      {isSelected && (
                        <div className="absolute -top-3.5 right-3 bg-[#0d1321] px-2 py-0.5 rounded-lg border border-white/10 flex items-center gap-1.5 z-10 text-[10px] font-semibold text-white/50">
                          <button onClick={(e) => moveElement(idx, -1, e)} className="hover:text-white">▲</button>
                          <button onClick={(e) => moveElement(idx, 1, e)} className="hover:text-white">▼</button>
                          <span className="text-white/20">|</span>
                          <span className="text-blue-400 font-bold">{el.type}</span>
                          <span className="text-white/20">|</span>
                          <button onClick={(e) => deleteElement(el.id, e)} className="text-red-400 hover:text-red-300">Delete</button>
                        </div>
                      )}

                      {/* Render Visual Preview Elements */}
                      {el.type === "Navbar" && (
                        <div className="bg-[#111827]/80 backdrop-blur px-4 py-2 border-b border-white/10 rounded-lg flex items-center font-bold text-white/90">
                          {el.props.title || "Navbar Title"}
                        </div>
                      )}
                      {el.type === "Heading" && (
                        <h2 className="text-2xl font-bold tracking-tight text-white mt-1">
                          {el.props.text || "Heading Text"}
                        </h2>
                      )}
                      {el.type === "Text" && (
                        <p className="text-sm text-white/60">
                          {el.props.text || "Text paragraph content."}
                        </p>
                      )}
                      {el.type === "Card" && (
                        <div className="p-4 bg-white/5 rounded-xl border border-white/5 shadow-md">
                          <h4 className="font-semibold text-sm text-white mb-2">{el.props.title || "Card Title"}</h4>
                          <p className="text-xs text-white/60">{el.props.content || "Card body text description."}</p>
                        </div>
                      )}
                      {el.type === "Button" && (
                        <button className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-lg text-sm font-semibold active:scale-95 transition">
                          {el.props.label || "Button Label"}
                        </button>
                      )}
                      {el.type === "Input" && (
                        <div className="w-full flex flex-col gap-1.5">
                          <label className="text-xs font-semibold text-white/60">{el.props.label || "Input Label"}</label>
                          <input
                            type="text"
                            disabled
                            placeholder={el.props.placeholder || "Enter text..."}
                            className="px-3 py-2 bg-white/5 rounded-lg border border-white/10 text-xs w-full text-white/60"
                          />
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </main>

        {/* Right Inspector & Code Panel */}
        <aside className="w-80 bg-[#0b0f19] border-l border-white/5 flex flex-col overflow-hidden">
          {/* Tab Selector */}
          <div className="flex border-b border-white/5 bg-[#080c14]">
            <button
              onClick={() => setActiveTab("props")}
              className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition ${activeTab === "props" ? "border-blue-500 text-blue-400 bg-white/5" : "border-transparent text-white/40 hover:text-white"}`}
            >
              Properties
            </button>
            <button
              onClick={() => setActiveTab("code")}
              className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition ${activeTab === "code" ? "border-blue-500 text-blue-400 bg-white/5" : "border-transparent text-white/40 hover:text-white"}`}
            >
              Code Editor
            </button>
          </div>

          <div className="flex-1 p-5 overflow-y-auto">
            {activeTab === "props" ? (
              <div>
                {!selectedElement ? (
                  <div className="text-center text-white/30 py-12 text-sm">Select an element on canvas to modify its properties.</div>
                ) : (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between mb-4 border-b border-white/5 pb-2">
                      <span className="text-xs font-semibold text-white/40 uppercase">Selected Element</span>
                      <span className="px-2 py-0.5 rounded bg-blue-500/10 text-blue-400 text-[10px] font-bold uppercase">{selectedElement.type}</span>
                    </div>

                    {selectedElement.type === "Navbar" && (
                      <div className="space-y-3">
                        <label className="text-xs text-white/60 font-semibold block">Navbar Title</label>
                        <input
                          type="text"
                          value={selectedElement.props.title || ""}
                          onChange={(e) => updateProp("title", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none"
                        />
                      </div>
                    )}

                    {(selectedElement.type === "Heading" || selectedElement.type === "Text") && (
                      <div className="space-y-3">
                        <label className="text-xs text-white/60 font-semibold block">Content Text</label>
                        <textarea
                          rows={4}
                          value={selectedElement.props.text || ""}
                          onChange={(e) => updateProp("text", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none"
                        />
                      </div>
                    )}

                    {selectedElement.type === "Card" && (
                      <div className="space-y-3">
                        <label className="text-xs text-white/60 font-semibold block">Card Title</label>
                        <input
                          type="text"
                          value={selectedElement.props.title || ""}
                          onChange={(e) => updateProp("title", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none mb-3"
                        />
                        <label className="text-xs text-white/60 font-semibold block">Card Content</label>
                        <textarea
                          rows={4}
                          value={selectedElement.props.content || ""}
                          onChange={(e) => updateProp("content", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none"
                        />
                      </div>
                    )}

                    {selectedElement.type === "Button" && (
                      <div className="space-y-3">
                        <label className="text-xs text-white/60 font-semibold block">Button Label</label>
                        <input
                          type="text"
                          value={selectedElement.props.label || ""}
                          onChange={(e) => updateProp("label", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none"
                        />
                      </div>
                    )}

                    {selectedElement.type === "Input" && (
                      <div className="space-y-3">
                        <label className="text-xs text-white/60 font-semibold block">Input Label</label>
                        <input
                          type="text"
                          value={selectedElement.props.label || ""}
                          onChange={(e) => updateProp("label", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none mb-3"
                        />
                        <label className="text-xs text-white/60 font-semibold block">Placeholder</label>
                        <input
                          type="text"
                          value={selectedElement.props.placeholder || ""}
                          onChange={(e) => updateProp("placeholder", e.target.value)}
                          className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white focus:border-blue-500 focus:outline-none"
                        />
                      </div>
                    )}
                  </div>
                )}
              </div>
            ) : (
              <div className="h-full flex flex-col">
                <p className="text-xs text-white/40 mb-2">Live generated .pyreact code structure:</p>
                <textarea
                  readOnly
                  value={generatedCode}
                  className="flex-1 w-full bg-[#05080f] p-3 font-mono text-[11px] text-blue-300 rounded-lg border border-white/5 focus:outline-none resize-none"
                />
              </div>
            )}
          </div>
        </aside>
      </div>

      {/* Floating Status Toast */}
      {toastMsg && (
        <div className="fixed bottom-6 right-6 z-50 px-5 py-3 bg-blue-600 rounded-xl text-white text-sm shadow-xl font-semibold animate-bounce">
          {toastMsg}
        </div>
      )}
    </div>
  );
}
